/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#define RCC_APB2ENR  (*((volatile unsigned long *)	0x40021018))
#define GPIOC_CRH (*((volatile unsigned long*)		0x40011004))
#define GPIOC_ODR (*((volatile unsigned long*)		0x4001100C))
#define TIM1_CNT (*((volatile unsigned long*) 		0x40012C24))
#define TIM1_PSC (*((volatile unsigned long*)		0x40012C28))
#define TIM1_ARR (*((volatile unsigned long*)		0x40012C2C))
#define TIM1_CR1 (*((volatile unsigned long*)		0x40012C00))



void GPIO_init(void){

	RCC_APB2ENR |= 0x0010;
	GPIOC_CRH |= 0x200000;
	GPIOC_ODR = 0;


}

void TIM1_init(){

	RCC_APB2ENR |= 0x0800;
	TIM1_CNT =0;
	TIM1_PSC = 8000;
	TIM1_ARR = 499;
	TIM1_CR1 |= 0;
}



//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

int main(void)
{
	GPIO_init();
	TIM1_init();

	TIM1_CR1 |= 1;

	while(1){

	if (TIM1_CNT == 499)
	{
		TIM1_CNT = 0;
		GPIOC_ODR ^= 0X2000;
	}


	}
    /* Loop forever */

}
